/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:01:42 GMT 2020
 */

package net.sourceforge.squirrel_sql.client.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.URL;
import java.net.URLStreamHandler;
import net.sourceforge.squirrel_sql.client.gui.HtmlViewerPanel;
import net.sourceforge.squirrel_sql.client.gui.IHtmlViewerPanelListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jboss.net.protocol.file.Handler;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HtmlViewerPanel_ESTest extends HtmlViewerPanel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      htmlViewerPanel0.gotoURL(uRL0);
      URL uRL1 = MockURL.getFileExample();
      htmlViewerPanel0.gotoURL(uRL1);
      htmlViewerPanel0.goForward();
      assertFalse(htmlViewerPanel0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      MockFile mockFile0 = new MockFile("", "");
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = mockFile0.toURL();
      htmlViewerPanel0.gotoURL(uRL1);
      htmlViewerPanel0.gotoURL(uRL0);
      htmlViewerPanel0.goBack();
      htmlViewerPanel0.goForward();
      assertFalse(htmlViewerPanel0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      htmlViewerPanel0.goBack();
      assertTrue(htmlViewerPanel0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      URL uRL0 = htmlViewerPanel0.getURL();
      assertNull(uRL0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Handler handler0 = new Handler();
      URL uRL0 = MockURL.URL("", ") not recognised.", 0, "-10-", (URLStreamHandler) handler0);
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getURL();
      assertEquals(") not recognised.", uRL1.getHost());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      org.jboss.net.protocol.resource.Handler handler0 = new org.jboss.net.protocol.resource.Handler();
      URL uRL0 = MockURL.URL("", "", 3554, "", (URLStreamHandler) handler0);
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getURL();
      assertEquals((-1), uRL1.getDefaultPort());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      URL uRL0 = htmlViewerPanel0.getHomeURL();
      assertNull(uRL0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Handler handler0 = new Handler();
      URL uRL0 = MockURL.URL("", ") not recognised.", 0, "-10-", (URLStreamHandler) handler0);
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getHomeURL();
      assertEquals("-10-", uRL1.getFile());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      org.jboss.net.protocol.resource.Handler handler0 = new org.jboss.net.protocol.resource.Handler();
      URL uRL0 = MockURL.URL("", "", 3554, "", (URLStreamHandler) handler0);
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getHomeURL();
      assertSame(uRL0, uRL1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      htmlViewerPanel0.goHome();
      // Undeclared exception!
      try { 
        htmlViewerPanel0.gotoURL(uRL0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      IHtmlViewerPanelListener iHtmlViewerPanelListener0 = mock(IHtmlViewerPanelListener.class, new ViolatedAssumptionAnswer());
      htmlViewerPanel0.addListener(iHtmlViewerPanelListener0);
      IHtmlViewerPanelListener iHtmlViewerPanelListener1 = mock(IHtmlViewerPanelListener.class, new ViolatedAssumptionAnswer());
      htmlViewerPanel0.addListener(iHtmlViewerPanelListener1);
      htmlViewerPanel0.setHomeURL((URL) null);
      assertFalse(htmlViewerPanel0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      IHtmlViewerPanelListener iHtmlViewerPanelListener0 = mock(IHtmlViewerPanelListener.class, new ViolatedAssumptionAnswer());
      htmlViewerPanel0.addListener(iHtmlViewerPanelListener0);
      IHtmlViewerPanelListener iHtmlViewerPanelListener1 = mock(IHtmlViewerPanelListener.class, new ViolatedAssumptionAnswer());
      htmlViewerPanel0.addListener(iHtmlViewerPanelListener1);
      URL uRL1 = MockURL.getFileExample();
      htmlViewerPanel0.gotoURL(uRL1);
      assertNotSame(uRL0, uRL1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      IHtmlViewerPanelListener iHtmlViewerPanelListener0 = mock(IHtmlViewerPanelListener.class, new ViolatedAssumptionAnswer());
      htmlViewerPanel0.addListener(iHtmlViewerPanelListener0);
      htmlViewerPanel0.refreshPage();
      assertFalse(htmlViewerPanel0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      htmlViewerPanel0.goHome();
      htmlViewerPanel0.goForward();
      assertTrue(htmlViewerPanel0.getFocusTraversalKeysEnabled());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      htmlViewerPanel0.goForward();
      assertFalse(htmlViewerPanel0.getIgnoreRepaint());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      htmlViewerPanel0.goBack();
      assertFalse(htmlViewerPanel0.isFocusCycleRoot());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      MockFile mockFile0 = new MockFile((String) null, "2RU5Nh`vg");
      URL uRL1 = mockFile0.toURL();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      htmlViewerPanel0.gotoURL(uRL1);
      htmlViewerPanel0.goBack();
      htmlViewerPanel0.gotoURL(uRL1);
      assertEquals("file", uRL1.getProtocol());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      MockFile mockFile0 = new MockFile("@X", "Nll 'hour' argument.");
      URL uRL1 = mockFile0.toURL();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL1);
      htmlViewerPanel0.gotoURL(uRL0);
      htmlViewerPanel0.goBack();
      htmlViewerPanel0.goForward();
      assertFalse(htmlViewerPanel0.isFocusTraversalPolicySet());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel((URL) null);
      // Undeclared exception!
      try { 
        htmlViewerPanel0.gotoURL((URL) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // URL == null
         //
         verifyException("net.sourceforge.squirrel_sql.client.gui.HtmlViewerPanel", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      htmlViewerPanel0.gotoURL(uRL0);
      assertEquals((-1), uRL0.getPort());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getHomeURL();
      assertEquals("http://www.someFakeButWellFormedURL.org/fooExample", uRL1.toExternalForm());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      htmlViewerPanel0.removeListener((IHtmlViewerPanelListener) null);
      assertFalse(htmlViewerPanel0.isFocusTraversalPolicyProvider());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      URL uRL0 = MockURL.getFtpExample();
      HtmlViewerPanel htmlViewerPanel0 = new HtmlViewerPanel(uRL0);
      URL uRL1 = htmlViewerPanel0.getURL();
      assertEquals("ftp://ftp.someFakeButWellFormedURL.org/fooExample", uRL1.toExternalForm());
  }
}
