/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:03:35 GMT 2020
 */

package com.aelitis.azureus.core.dht.router.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.aelitis.azureus.core.dht.DHTLogger;
import com.aelitis.azureus.core.dht.router.DHTRouterContact;
import com.aelitis.azureus.core.dht.router.DHTRouterContactAttachment;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterImpl;
import com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

 
public class DHTRouterNodeImplTest { 

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(778, 778, (-1471), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = (DHTRouterContactImpl)dHTRouterImpl0.contactDead(byteArray0, true);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl1 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 26);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      assertTrue(dHTRouterContactImpl0.isReplacement());
      assertFalse(dHTRouterContactImpl0.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(622, 1, 622, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 447);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 622);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      assertFalse(dHTRouterContactImpl0.isReplacement());
      assertTrue(dHTRouterContactImpl0.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((-686)).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-686), (-686), (-686), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((-1001)).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      assertTrue(dHTRouterContactImpl0.isAlive());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment2, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1);
      DHTRouterContactImpl dHTRouterContactImpl1 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, true);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 1);
      assertFalse(dHTRouterContact0.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(15, 15, 15, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, true);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 15);
      DHTRouterContact dHTRouterContact1 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-228));
      assertSame(dHTRouterContact1, dHTRouterContact0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-3209), (-3209), 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      byte[] byteArray1 = new byte[8];
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray1);
      dHTRouterNodeImpl0.split((DHTRouterNodeImpl) null, dHTRouterNodeImpl0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)16).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte)16, (byte)16, (byte)16, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, false);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment2, false);
      assertNotNull(dHTRouterContactImpl1);
      assertTrue(dHTRouterContactImpl1.isFailing());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte)0, (byte)0, (byte)0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      byte[] byteArray1 = new byte[6];
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray1, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.addNode(dHTRouterContactImpl0);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray1, dHTRouterContactAttachment2, true);
      assertTrue(dHTRouterContactImpl1.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(285, 15, 285, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      byte[] byteArray1 = new byte[1];
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray1);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray1, (DHTRouterContactAttachment) null, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-3120));
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray1, (DHTRouterContactAttachment) null, false);
      assertFalse(dHTRouterContactImpl1.isFailing());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 1526, false, linkedList0);
      dHTRouterNodeImpl0.setLastLookupTime();
      long long0 = dHTRouterNodeImpl0.getTimeSinceLastLookup();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 59, true, linkedList0);
      long long0 = dHTRouterNodeImpl0.getTimeSinceLastLookup();
      assertEquals(1392409281320L, long0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(4052, 4052, 1468, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1342);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      assertFalse(dHTRouterContactImpl0.isReplacement());
      
      List list0 = dHTRouterNodeImpl0.getReplacements();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1509, 1509, 1465, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterContactImpl dHTRouterContactImpl0 = (DHTRouterContactImpl)dHTRouterImpl0.contactDead(byteArray0, false);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-1462));
      List list0 = dHTRouterNodeImpl0.getReplacements();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(4917, 639, 639, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, 989, true, linkedList0);
      dHTRouterNodeImpl0.split(dHTRouterNodeImpl0, dHTRouterNodeImpl0);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = dHTRouterNodeImpl0.getLeft();
      assertSame(dHTRouterNodeImpl1, dHTRouterNodeImpl0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      byte[] byteArray0 = new byte[17];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1844, 1844, 1844, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      int int0 = dHTRouterNodeImpl0.getDepth();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 989, true, linkedList0);
      int int0 = dHTRouterNodeImpl0.getDepth();
      assertEquals(989, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte) (-63), (byte)0, (-81), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, (-81), true, linkedList0);
      int int0 = dHTRouterNodeImpl0.getDepth();
      assertEquals((-81), int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 2185, 177, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      dHTRouterNodeImpl0.split((DHTRouterNodeImpl) null, (DHTRouterNodeImpl) null);
      List list0 = dHTRouterNodeImpl0.getBuckets();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)0).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte)16, 68, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)16).when(dHTRouterContactAttachment1).getInstanceID();
      doReturn(45110).when(dHTRouterContactAttachment1).getMaxFailForLiveCount();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      List list0 = dHTRouterNodeImpl0.getBuckets();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1739, 0, 1739, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      boolean boolean0 = dHTRouterNodeImpl0.containsRouterNodeID();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 2048, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, (-2346), false, linkedList0);
      boolean boolean0 = dHTRouterNodeImpl0.containsRouterNodeID();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(65536, 267, 256, byteArray0, (DHTRouterContactAttachment) null, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      String string0 = dHTRouterNodeImpl0.contactsToString(linkedList0);
      assertEquals("{}", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte)16, 70, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)16).when(dHTRouterContactAttachment1).getInstanceID();
      doReturn(0).when(dHTRouterContactAttachment1).getMaxFailForLiveCount();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, false);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-2789));
      assertFalse(dHTRouterContact0.isAlive());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.updateExistingNode(byteArray0, (DHTRouterContactAttachment) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Object object0 = new Object();
      linkedList0.add(object0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 15, false, linkedList0);
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment0, false);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 1526, false, linkedList0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.requestNodeAdd((DHTRouterContactImpl) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 91, true, linkedList0);
      linkedList0.add((Object) dHTRouterNodeImpl0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.print("wi~/Pm)[(<", "wi~/Pm)[(<");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl cannot be cast to com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.contactsToString((List) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 43, true, linkedList0);
      linkedList0.add((Object) "");
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.contactsToString(linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.alive((DHTRouterContactImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1526, 1526, 1526, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, false);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, (-2092), false, linkedList0);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-1406));
      linkedList0.add("");
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.alive(dHTRouterContactImpl0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 1349, false, linkedList0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.addReplacement((DHTRouterContactImpl) null, 1349);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment0, false);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1526, 2026, (byte) (-9), byteArray0, dHTRouterContactAttachment1, dHTLogger0);
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, (-5752), true, linkedList0);
      linkedList0.add((Object) dHTRouterImpl0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 2026);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.aelitis.azureus.core.dht.router.impl.DHTRouterImpl cannot be cast to com.aelitis.azureus.core.dht.router.impl.DHTRouterContactImpl
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, (-2358), false, linkedList0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.addNode((DHTRouterContactImpl) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(622, 1, 622, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(dHTRouterContactAttachment1).getInstanceID();
      doReturn(0).when(dHTRouterContactAttachment1).getMaxFailForLiveCount();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      dHTRouterContactImpl0.setFailed();
      dHTRouterNodeImpl0.alive(dHTRouterContactImpl0);
      assertTrue(dHTRouterContactImpl0.isAlive());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      dHTRouterNodeImpl0.split(dHTRouterNodeImpl0, dHTRouterNodeImpl0);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.print("", "");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(45100, (byte)72, (-1), (byte[]) null, (DHTRouterContactAttachment) null, dHTLogger0);
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl(dHTRouterImpl0, (-833), false, linkedList0);
      dHTRouterNodeImpl0.print(";|NPn%k_", "{}");
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((byte)16, 70, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)16).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (-2789));
      dHTRouterNodeImpl0.print("/K&$av", "org.bouncycastle.jce.provider.JDKPSSSigner$SHA256withRSA");
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1389, 1, 0, byteArray0, (DHTRouterContactAttachment) null, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      DHTRouterNodeImpl dHTRouterNodeImpl1 = new DHTRouterNodeImpl(dHTRouterImpl0, (byte)37, false, linkedList0);
      dHTRouterNodeImpl1.split(dHTRouterNodeImpl0, dHTRouterNodeImpl0);
      dHTRouterNodeImpl1.print("+V{AO_BsIl", "");
      assertNotSame(dHTRouterNodeImpl1, dHTRouterNodeImpl0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((int)(byte)0).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(70, 70, 70, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.requestNodeAdd(dHTRouterContactImpl0, false);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn((-2645)).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment2, false);
      assertFalse(dHTRouterContactImpl1.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(0, 0, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      dHTRouterNodeImpl0.addNode(dHTRouterContactImpl0);
      dHTRouterNodeImpl0.requestNodeAdd(dHTRouterContactImpl0, true);
      assertTrue(dHTRouterContactImpl0.isAlive());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      LinkedList<DHTRouterContactImpl> linkedList0 = new LinkedList<DHTRouterContactImpl>();
      DHTRouterNodeImpl dHTRouterNodeImpl0 = new DHTRouterNodeImpl((DHTRouterImpl) null, 2664, false, linkedList0);
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForUnknownCount();
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment0, false);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      DHTRouterContactImpl dHTRouterContactImpl1 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, false);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 1);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      assertNotSame(dHTRouterContactImpl0, dHTRouterContact0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(dHTRouterContactAttachment0).getInstanceID();
      doReturn(0, 0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, true);
      DHTRouterContactImpl dHTRouterContactImpl1 = (DHTRouterContactImpl)dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl1, true);
      assertTrue(dHTRouterContactImpl0.isBucketEntry());
      assertFalse(dHTRouterContactImpl0.isReplacement());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0).when(dHTRouterContactAttachment0).getMaxFailForLiveCount();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, true);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterNodeImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(3308).when(dHTRouterContactAttachment0).getInstanceID();
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(dHTRouterContactAttachment1).getInstanceID();
      doReturn(3308).when(dHTRouterContactAttachment1).getMaxFailForLiveCount();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      dHTRouterNodeImpl0.dead(dHTRouterContactImpl0, false);
      assertTrue(dHTRouterContactImpl0.isFailing());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-686), (-686), (-686), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger1 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl1 = new DHTRouterImpl((-686), (-686), 669, byteArray0, dHTRouterContactAttachment1, dHTLogger1);
      DHTRouterContactImpl dHTRouterContactImpl0 = (DHTRouterContactImpl)dHTRouterImpl1.contactDead(byteArray0, false);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      dHTRouterContactImpl0.setAlive();
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1526);
      dHTRouterNodeImpl0.alive(dHTRouterContactImpl0);
      assertFalse(dHTRouterContactImpl0.isBucketEntry());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(3308, 3308, 3308, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 3308);
      dHTRouterNodeImpl0.alive(dHTRouterContactImpl0);
      assertTrue(dHTRouterContactImpl0.isAlive());
      assertTrue(dHTRouterContactImpl0.hasBeenAlive());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(2180, 2180, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      byte[] byteArray1 = new byte[3];
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray1);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray1, dHTRouterContactAttachment1, true);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment2, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, (byte) (-69));
      dHTRouterNodeImpl0.alive(dHTRouterContactImpl0);
      assertTrue(dHTRouterContactImpl0.isAlive());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(2180, 2180, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      byte[] byteArray1 = new byte[3];
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray1);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment1).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment1, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (byte) (-69));
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray1, dHTRouterContactAttachment2, true);
      assertNull(dHTRouterContactImpl1);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-1895), (-1), (-1), byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      byte[] byteArray1 = new byte[5];
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray1, (DHTRouterContactAttachment) null, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, (byte)112);
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray1, (DHTRouterContactAttachment) null, true);
      assertTrue(dHTRouterContactImpl1.hasBeenAlive());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-1895), (-1), (-1), byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      byte[] byteArray1 = new byte[5];
      DHTRouterContactImpl dHTRouterContactImpl0 = dHTRouterNodeImpl0.updateExistingNode(byteArray1, (DHTRouterContactAttachment) null, true);
      assertNull(dHTRouterContactImpl0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1892, (-2539), (-2539), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      List list0 = dHTRouterNodeImpl0.getBuckets();
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, true);
      byte[] byteArray1 = new byte[2];
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger1 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl1 = new DHTRouterImpl(1892, 1892, 1892, byteArray1, dHTRouterContactAttachment2, dHTLogger1);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = new DHTRouterNodeImpl(dHTRouterImpl1, 1892, true, list0);
      dHTRouterNodeImpl1.addReplacement(dHTRouterContactImpl0, 368);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl1.addReplacement(dHTRouterContactImpl0, 368);
      assertTrue(dHTRouterContact0.isAlive());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1892, (-2539), (-2539), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      List list0 = dHTRouterNodeImpl0.getBuckets();
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, true);
      byte[] byteArray1 = new byte[8];
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger1 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl1 = new DHTRouterImpl(1892, 1892, 1892, byteArray1, dHTRouterContactAttachment2, dHTLogger1);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = new DHTRouterNodeImpl(dHTRouterImpl1, 1892, true, list0);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl1.addReplacement(dHTRouterContactImpl0, 378);
      assertNotNull(dHTRouterContact0);
      
      dHTRouterNodeImpl1.alive(dHTRouterContactImpl0);
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactAttachment dHTRouterContactAttachment1 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, dHTRouterContactAttachment1, false);
      DHTRouterContactAttachment dHTRouterContactAttachment2 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(dHTRouterContactAttachment2).getInstanceID();
      DHTRouterContactImpl dHTRouterContactImpl1 = dHTRouterNodeImpl0.updateExistingNode(byteArray0, dHTRouterContactAttachment2, false);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 1);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1);
      assertNull(dHTRouterContact0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, false);
      DHTRouterContactImpl dHTRouterContactImpl1 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 1);
      assertTrue(dHTRouterContact0.hasBeenAlive());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, false);
      DHTRouterContactImpl dHTRouterContactImpl1 = (DHTRouterContactImpl)dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 1);
      DHTRouterContactImpl dHTRouterContactImpl2 = (DHTRouterContactImpl)dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 1);
      assertFalse(dHTRouterContactImpl2.isFailing());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(3308, 3308, 3308, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, true);
      DHTRouterContactImpl dHTRouterContactImpl1 = (DHTRouterContactImpl)dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 3308);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl1, 3308);
      // Undeclared exception!
      try { 
        dHTRouterNodeImpl0.print("', value '", "', value '");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.aelitis.azureus.core.dht.router.impl.DHTRouterImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1, 1, 1, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, true);
      DHTRouterContact dHTRouterContact0 = dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 0);
      assertNull(dHTRouterContact0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(3308, 3308, 3308, byteArray0, (DHTRouterContactAttachment) null, (DHTLogger) null);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterContactImpl dHTRouterContactImpl0 = new DHTRouterContactImpl(byteArray0, (DHTRouterContactAttachment) null, true);
      dHTRouterNodeImpl0.addReplacement(dHTRouterContactImpl0, 3308);
      dHTRouterNodeImpl0.split((DHTRouterNodeImpl) null, (DHTRouterNodeImpl) null);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(0, 0, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      dHTRouterNodeImpl0.split(dHTRouterNodeImpl0, dHTRouterNodeImpl0);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = dHTRouterNodeImpl0.getRight();
      assertSame(dHTRouterNodeImpl1, dHTRouterNodeImpl0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(1509, 1509, 1465, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      List list0 = dHTRouterNodeImpl0.getReplacements();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      byte[] byteArray0 = new byte[4];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl(0, 0, 0, byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = dHTRouterNodeImpl0.getRight();
      assertNull(dHTRouterNodeImpl1);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      byte[] byteArray0 = new byte[0];
      DHTRouterContactAttachment dHTRouterContactAttachment0 = mock(DHTRouterContactAttachment.class, new ViolatedAssumptionAnswer());
      DHTLogger dHTLogger0 = mock(DHTLogger.class, new ViolatedAssumptionAnswer());
      DHTRouterImpl dHTRouterImpl0 = new DHTRouterImpl((-686), (-686), (-686), byteArray0, dHTRouterContactAttachment0, dHTLogger0);
      DHTRouterNodeImpl dHTRouterNodeImpl0 = dHTRouterImpl0.findNode(byteArray0);
      DHTRouterNodeImpl dHTRouterNodeImpl1 = dHTRouterNodeImpl0.getLeft();
      assertNull(dHTRouterNodeImpl1);
  }
}
