/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:36:45 GMT 2020
 */

package org.sourceforge.ifx.basetypes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.sourceforge.ifx.basetypes.IFXBase64Binary;
import org.sourceforge.ifx.basetypes.IFXDecimal;
import org.sourceforge.ifx.basetypes.IFXHexBinary;
import org.sourceforge.ifx.basetypes.IFXObject;
import org.sourceforge.ifx.basetypes.IFXString;

 
public class IFXObjectTest { 

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IFXObject iFXObject0 = new IFXObject();
      IFXObject iFXObject1 = new IFXObject();
      boolean boolean0 = iFXObject0.equals(iFXObject1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IFXDecimal iFXDecimal0 = new IFXDecimal();
      // Undeclared exception!
      try { 
        iFXDecimal0.equals(iFXDecimal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.sourceforge.ifx.basetypes.IFXDecimal", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IFXObject iFXObject0 = new IFXObject();
      IFXHexBinary iFXHexBinary0 = new IFXHexBinary();
      boolean boolean0 = iFXObject0.equals(iFXHexBinary0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IFXHexBinary iFXHexBinary0 = new IFXHexBinary();
      iFXHexBinary0.setString("");
      String string0 = iFXHexBinary0.toString();
      assertEquals("org.sourceforge.ifx.basetypes.IFXHexBinary = {\n  Bytes = [\n\n  ]\n  String = Exception! java.lang.ClassCastException: java.lang.String cannot be cast to org.sourceforge.ifx.basetypes.IFXObject\n}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IFXBase64Binary iFXBase64Binary0 = new IFXBase64Binary();
      iFXBase64Binary0.setString("2ipB>.G/'ChcT");
      String string0 = iFXBase64Binary0.toString();
      assertEquals("org.sourceforge.ifx.basetypes.IFXBase64Binary = {\n  Bytes = [\n    [0]:Exception! java.lang.ClassCastException: java.lang.Byte cannot be cast to org.sourceforge.ifx.basetypes.IFXObject\n  }", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IFXString iFXString0 = new IFXString();
      String string0 = iFXString0.toString();
      assertEquals("org.sourceforge.ifx.basetypes.IFXString = {\n  String = NULL\n}", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IFXObject iFXObject0 = new IFXObject();
      boolean boolean0 = iFXObject0.equals("N4T>hYt=u");
      assertFalse(boolean0);
  }
}
