/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu May 07 07:51:53 GMT 2020
 */

package com.sap.managementconsole.soap.axis.sapcontrol;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class DirEntry_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.sap.managementconsole.soap.axis.sapcontrol.DirEntry"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("log4j.configuration", "SUT.log4j.properties"); 
    java.lang.System.setProperty("user.dir", "/home/test-smell/generation-scripts/projects/101_netweaver"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(DirEntry_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.axis.utils.IDKey",
      "org.apache.axis.deployment.wsdd.WSDDConstants",
      "org.apache.axis.message.SOAPEnvelope",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.axis.wsdl.symbolTable.BaseTypeMapping",
      "org.apache.log4j.or.RendererMap",
      "org.apache.axis.constants.Style$Type",
      "org.apache.axis.description.FieldDesc",
      "org.apache.axis.InternalException",
      "org.apache.axis.description.OperationDesc",
      "org.apache.axis.encoding.Deserializer",
      "org.apache.axis.wsdl.symbolTable.UndefinedElement",
      "org.apache.log4j.Level",
      "org.apache.commons.discovery.tools.ClassUtils",
      "org.apache.axis.encoding.DeserializationContext$NullLexicalHandler",
      "org.apache.axis.strategies.InvocationStrategy",
      "org.apache.axis.message.SOAPFault",
      "org.apache.axis.message.SOAPFaultBuilder",
      "org.apache.axis.description.TypeDesc",
      "org.apache.axis.components.logger.LogFactory$1",
      "org.apache.axis.utils.cache.JavaClass",
      "org.apache.log4j.spi.RootCategory",
      "org.apache.axis.Handler",
      "org.apache.axis.description.FaultDesc",
      "org.apache.axis.encoding.TypeMappingRegistry",
      "org.apache.axis.wsdl.symbolTable.BindingEntry",
      "org.apache.axis.wsdl.symbolTable.MessageEntry",
      "org.apache.log4j.spi.Filter",
      "org.apache.axis.wsdl.symbolTable.Parameter",
      "org.apache.axis.encoding.Serializer",
      "org.apache.axis.soap.SOAP11Constants",
      "org.apache.axis.message.SOAPFaultDetailsBuilder",
      "org.apache.axis.SimpleChain",
      "org.apache.log4j.CategoryKey",
      "org.apache.axis.message.MessageElement",
      "org.apache.axis.message.HeaderBuilder",
      "org.apache.axis.encoding.ser.BeanDeserializer",
      "org.apache.axis.wsdl.symbolTable.Type",
      "org.apache.log4j.Layout",
      "org.apache.commons.discovery.resource.names.DiscoverNamesInAlternateManagedProperties",
      "org.apache.axis.encoding.DeserializerImpl",
      "org.apache.axis.encoding.SerializationContext",
      "org.apache.axis.attachments.Attachments",
      "org.apache.axis.ConfigurationException",
      "org.apache.axis.message.MimeHeaders",
      "org.apache.axis.soap.SOAP12Constants",
      "org.apache.commons.discovery.log.SimpleLog",
      "org.apache.axis.message.EnvelopeBuilder",
      "org.apache.axis.utils.ByteArray",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.ProvisionNode",
      "org.apache.axis.encoding.ser.BeanDeserializerFactory",
      "org.apache.log4j.Hierarchy",
      "org.apache.commons.discovery.tools.DefaultClassHolder",
      "com.sap.managementconsole.soap.axis.sapcontrol.DirEntry",
      "org.apache.axis.wsdl.symbolTable.CollectionType",
      "org.apache.axis.wsdl.symbolTable.Undefined",
      "org.apache.commons.discovery.ResourceNameIterator",
      "org.apache.axis.constants.Enum$Type",
      "org.apache.axis.message.NullAttributes",
      "org.apache.axis.schema.SchemaVersion1999",
      "org.apache.commons.discovery.ResourceNameDiscover",
      "org.apache.commons.discovery.tools.ManagedProperties$1",
      "org.apache.axis.wsdl.symbolTable.PortTypeEntry",
      "org.apache.axis.description.ServiceDesc",
      "org.apache.axis.components.encoding.XMLEncoder",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.OptionHandler",
      "org.apache.axis.utils.LockableHashtable",
      "org.apache.axis.utils.cache.ClassCache",
      "org.apache.axis.components.logger.LogFactory",
      "org.apache.axis.strategies.WSDLGenStrategy",
      "org.apache.log4j.spi.ErrorHandler",
      "org.apache.log4j.spi.VectorWriter",
      "org.apache.axis.message.IDResolver",
      "org.apache.commons.discovery.tools.ManagedProperties$Value",
      "org.apache.commons.discovery.tools.SPInterface",
      "org.apache.log4j.spi.RendererSupport",
      "org.apache.axis.SimpleTargetedChain",
      "org.apache.axis.message.RPCParam",
      "org.apache.axis.encoding.TypeMappingImpl",
      "org.apache.axis.constants.Enum",
      "org.apache.axis.message.Detail",
      "org.apache.commons.discovery.DiscoveryException",
      "org.apache.commons.discovery.ResourceClass",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.axis.wsdl.fromJava.Namespaces",
      "org.apache.axis.encoding.ser.BaseDeserializerFactory",
      "org.apache.axis.message.SOAPFaultCodeBuilder",
      "org.apache.commons.discovery.ResourceIterator",
      "org.apache.axis.encoding.Target",
      "org.apache.commons.discovery.ResourceClassIterator",
      "org.apache.log4j.or.ObjectRenderer",
      "org.apache.axis.HandlerIterationStrategy",
      "org.apache.axis.encoding.TypeMappingDelegate",
      "org.apache.commons.discovery.Resource",
      "org.apache.axis.message.RPCHandler",
      "org.apache.axis.message.Text",
      "org.apache.log4j.Logger",
      "org.apache.axis.wsdl.fromJava.Types",
      "org.apache.axis.encoding.DeserializerFactory",
      "org.apache.axis.message.RPCElement",
      "org.apache.axis.wsdl.fromJava.Types$2",
      "org.apache.axis.client.AxisClient",
      "org.apache.axis.session.Session",
      "org.apache.axis.constants.Style",
      "org.apache.axis.wsdl.fromJava.Types$1",
      "org.apache.axis.wsdl.symbolTable.PortEntry",
      "org.apache.axis.MessageContext",
      "org.apache.axis.Chain",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category",
      "org.apache.axis.wsdl.symbolTable.Element",
      "org.apache.axis.wsdl.symbolTable.MimeInfo",
      "org.apache.commons.discovery.jdk.JDKHooks",
      "org.apache.log4j.spi.RepositorySelector",
      "org.apache.axis.wsdl.symbolTable.CollectionTE",
      "org.apache.axis.message.SOAPHeader",
      "org.apache.axis.message.EnvelopeHandler",
      "org.apache.axis.TargetedChain",
      "org.apache.axis.AxisEngine",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.axis.description.ParameterDesc",
      "org.apache.log4j.spi.Configurator",
      "org.apache.commons.discovery.tools.ManagedProperties",
      "org.apache.axis.description.ElementDesc",
      "org.apache.axis.wsdl.symbolTable.BaseType",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.commons.discovery.log.DiscoveryLogFactory",
      "org.apache.axis.utils.BeanUtils$1",
      "org.apache.commons.discovery.resource.names.ResourceNameDiscoverImpl",
      "org.apache.axis.handlers.BasicHandler",
      "org.apache.log4j.spi.LocationInfo",
      "org.apache.axis.encoding.DeserializationContext",
      "org.apache.axis.constants.Use$Type",
      "org.apache.axis.Part",
      "org.apache.axis.message.SOAPFaultReasonBuilder",
      "org.apache.axis.message.SOAPBodyElement",
      "org.apache.axis.message.SAX2EventRecorder",
      "org.apache.axis.AxisProperties",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.commons.discovery.resource.names.DiscoverMappedNames",
      "org.apache.commons.logging.impl.Log4JLogger",
      "org.apache.axis.Message",
      "org.apache.axis.encoding.SerializerFactory",
      "org.apache.axis.attachments.IncomingAttachmentStreams",
      "org.apache.axis.AxisFault",
      "org.apache.log4j.Appender",
      "org.apache.axis.message.InputStreamBody",
      "org.apache.axis.schema.SchemaVersion2001",
      "org.apache.axis.encoding.TypeMapping",
      "org.apache.axis.EngineConfiguration",
      "org.apache.axis.message.SOAPHeaderElement",
      "org.apache.axis.wsdl.symbolTable.CollectionElement",
      "org.apache.axis.schema.SchemaVersion",
      "org.apache.commons.discovery.jdk.JDK12Hooks",
      "org.apache.axis.message.SOAPFaultElement",
      "org.apache.axis.wsdl.symbolTable.SymbolTable",
      "org.apache.axis.encoding.ser.BeanSerializer",
      "org.apache.axis.utils.Mapping",
      "org.apache.axis.attachments.IncomingAttachmentStreams$IncomingAttachmentInputStream",
      "org.apache.axis.message.NodeImpl",
      "org.apache.axis.utils.BeanPropertyDescriptor",
      "org.apache.log4j.spi.HierarchyEventListener",
      "org.apache.axis.SOAPPart",
      "org.apache.axis.encoding.Callback",
      "org.apache.commons.discovery.jdk.PsuedoSystemClassLoader",
      "org.apache.axis.wsdl.symbolTable.UndefinedType",
      "org.apache.axis.handlers.soap.SOAPService",
      "org.apache.axis.Constants",
      "org.apache.axis.wsdl.symbolTable.DefinedType",
      "org.apache.axis.message.SOAPHandler",
      "org.apache.axis.constants.Use",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.apache.axis.soap.SOAPConstants",
      "org.apache.log4j.spi.LoggingEvent",
      "org.apache.axis.schema.SchemaVersion2000",
      "org.apache.log4j.spi.NullWriter",
      "org.apache.axis.utils.BeanUtils",
      "org.apache.axis.wsdl.symbolTable.DefinedElement",
      "org.apache.axis.wsdl.symbolTable.Parameters",
      "org.apache.log4j.spi.ThrowableInformation",
      "org.apache.axis.message.SOAPBody",
      "org.apache.log4j.Priority",
      "org.apache.axis.message.BodyBuilder",
      "org.apache.axis.wsdl.symbolTable.SymTabEntry",
      "org.apache.axis.wsdl.symbolTable.TypeEntry",
      "org.apache.log4j.spi.LoggerRepository",
      "org.apache.log4j.LogManager",
      "org.apache.axis.encoding.ser.BaseFactory",
      "org.apache.axis.wsdl.symbolTable.ServiceEntry"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(DirEntry_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.axis.components.logger.LogFactory$1",
      "org.apache.axis.components.logger.LogFactory",
      "org.apache.log4j.Level",
      "org.apache.log4j.Priority",
      "org.apache.commons.logging.impl.Log4JLogger",
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootCategory",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "org.apache.axis.description.TypeDesc",
      "org.apache.axis.description.FieldDesc",
      "org.apache.axis.description.ElementDesc",
      "com.sap.managementconsole.soap.axis.sapcontrol.DirEntry",
      "org.apache.axis.message.SOAPHandler",
      "org.apache.axis.encoding.DeserializerImpl",
      "org.apache.axis.encoding.ser.BeanDeserializer",
      "org.apache.axis.encoding.ser.BaseFactory",
      "org.apache.axis.encoding.ser.BaseDeserializerFactory",
      "org.apache.axis.encoding.ser.BeanDeserializerFactory",
      "org.apache.axis.utils.BeanUtils",
      "org.apache.axis.utils.BeanUtils$1",
      "org.apache.axis.AxisFault",
      "org.apache.axis.utils.BeanPropertyDescriptor",
      "org.apache.axis.encoding.ser.BeanSerializer"
    );
  }
}
