/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 09:09:57 GMT 2020
 */

package com.liferay.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.util.PwdGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

 
public class PwdGeneratorTest { 

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String string0 = PwdGenerator.getSecurePassword("06CIOVbh", (-2374), false);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = PwdGenerator.getSecurePassword("06CIOVbh", (-2374));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = PwdGenerator.getPassword("vbh", (-302), true);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = PwdGenerator.getPassword("06CIOVbh", (-65));
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getSecurePassword("", 97, true);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getSecurePassword((String) null, 1236, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PwdGenerator.getSecurePassword(3090);
      PwdGenerator.getPassword(3090);
      PwdGenerator.getPassword("com.liferay.portal.kernel.log.Jdk14LogFactoryImpl", 3090);
      // Undeclared exception!
      PwdGenerator.getSecurePassword("06CIOVbh", 1574);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getSecurePassword("", 435);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getSecurePassword((String) null, 3126);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getPassword("", 1221, true);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getPassword((String) null, 0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PwdGenerator.getPassword("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 2816, false);
      PwdGenerator.getPassword("/", 2842);
      PwdGenerator.getPassword("com.liferay.portal.kernel.log.LogWrapper", 2816, false);
      // Undeclared exception!
      PwdGenerator.getPassword("W)t-Mdyo/h#|9qdNw", 2816);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        PwdGenerator.getPassword((String) null, (-344));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = PwdGenerator.getPassword("0123456789", 0, false);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = PwdGenerator.getSecurePassword("0123456789", (-236), true);
      assertEquals("0", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PwdGenerator pwdGenerator0 = new PwdGenerator();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PwdGenerator.getSecurePassword("TT06CIIO", 4315);
      PwdGenerator.getPassword("abcdefghijklmnopqrstuvwxyz", 4315);
      // Undeclared exception!
      PwdGenerator.getSecurePassword(0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = PwdGenerator.getPinNumber();
      assertEquals("0123", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = PwdGenerator.getSecurePassword();
      assertEquals("06CIOVbh", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String string0 = PwdGenerator.getPassword();
      assertEquals("06CIOVbh", string0);
  }
}
