/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 07:57:05 GMT 2020
 */

package net.sourceforge.squirrel_sql.client.update.gui.installer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import net.sourceforge.squirrel_sql.client.update.UpdateUtil;
import net.sourceforge.squirrel_sql.client.update.UpdateUtilImpl;
import net.sourceforge.squirrel_sql.client.update.gui.ArtifactStatus;
import net.sourceforge.squirrel_sql.client.update.gui.installer.ArtifactInstallerFactory;
import net.sourceforge.squirrel_sql.client.update.gui.installer.ArtifactInstallerFactoryImpl;
import net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl;
import net.sourceforge.squirrel_sql.fw.util.IOUtilities;
import net.sourceforge.squirrel_sql.fw.util.IOUtilitiesImpl;
import net.sourceforge.squirrel_sql.fw.util.ScriptLineFixer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PreLaunchHelperImpl_ESTest extends PreLaunchHelperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      LinkedList<ScriptLineFixer> linkedList0 = new LinkedList<ScriptLineFixer>();
      preLaunchHelperImpl0.setScriptLineFixers(linkedList0);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("update/changeList.xml");
      FileSystemHandling.createFolder(evoSuiteFile0);
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      preLaunchHelperImpl0.installUpdates(false);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      preLaunchHelperImpl0.setScriptLocation("");
      String string0 = preLaunchHelperImpl0.getScriptLocation();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      IOUtilitiesImpl iOUtilitiesImpl0 = new IOUtilitiesImpl();
      preLaunchHelperImpl0.setIoutils(iOUtilitiesImpl0);
      try { 
        preLaunchHelperImpl0.updateLaunchScript();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.setUpdateUtil((UpdateUtil) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // setUpdateUtil: Argument util cannot be null
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.Utilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.setIoutils((IOUtilities) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // setIoutils: Argument ioutils cannot be null
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.Utilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.setArtifactInstallerFactory((ArtifactInstallerFactory) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // setArtifactInstallerFactory: Argument artifactInstallerFactory cannot be null
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.Utilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.restoreFromBackup();
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.installUpdates(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      LinkedList<ArtifactStatus> linkedList0 = new LinkedList<ArtifactStatus>();
      FileSystemHandling.shouldAllThrowIOExceptions();
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      updateUtilImpl0.saveChangeList(linkedList0);
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.installUpdates(true);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      Vector<ArtifactStatus> vector0 = new Vector<ArtifactStatus>();
      updateUtilImpl0.saveChangeList(vector0);
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      preLaunchHelperImpl0.installUpdates(false);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/home/apaniche/test-smell/generation-scripts/projects/102_squirrel-sql");
      FileSystemHandling.setPermissions(evoSuiteFile0, false, false, false);
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.copySplashImage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.copySplashImage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("icons");
      FileSystemHandling.createFolder(evoSuiteFile0);
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.copySplashImage();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      preLaunchHelperImpl0.setScriptLocation("");
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.updateLaunchScript();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("net.sourceforge.squirrel_sql.client.update.gui.installer.PreLaunchHelperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      LinkedList<ArtifactStatus> linkedList0 = new LinkedList<ArtifactStatus>();
      ArtifactStatus artifactStatus0 = new ArtifactStatus();
      linkedList0.add(artifactStatus0);
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      updateUtilImpl0.saveChangeList(linkedList0);
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.installUpdates(true);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      preLaunchHelperImpl0.installUpdates(false);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      // Undeclared exception!
      try { 
        preLaunchHelperImpl0.setScriptLineFixers((List<ScriptLineFixer>) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // setScriptLineFixers: Argument scriptLineFixers cannot be null
         //
         verifyException("net.sourceforge.squirrel_sql.fw.util.Utilities", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      IOUtilitiesImpl iOUtilitiesImpl0 = new IOUtilitiesImpl();
      preLaunchHelperImpl0.setIoutils(iOUtilitiesImpl0);
      try { 
        preLaunchHelperImpl0.copySplashImage();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // /home/apaniche/test-smell/generation-scripts/projects/102_squirrel-sql/update/downloads/core/squirrel-sql.jar (No such file or directory)
         //
         verifyException("java.util.zip.ZipFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      preLaunchHelperImpl0.setScriptLocation("Ll");
      String string0 = preLaunchHelperImpl0.getScriptLocation();
      assertEquals("Ll", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      String string0 = preLaunchHelperImpl0.getScriptLocation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      ArtifactInstallerFactoryImpl artifactInstallerFactoryImpl0 = new ArtifactInstallerFactoryImpl();
      preLaunchHelperImpl0.setArtifactInstallerFactory(artifactInstallerFactoryImpl0);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PreLaunchHelperImpl preLaunchHelperImpl0 = new PreLaunchHelperImpl();
      LinkedList<ArtifactStatus> linkedList0 = new LinkedList<ArtifactStatus>();
      ArtifactStatus artifactStatus0 = new ArtifactStatus();
      linkedList0.add(artifactStatus0);
      UpdateUtilImpl updateUtilImpl0 = new UpdateUtilImpl();
      updateUtilImpl0.saveChangeList(linkedList0);
      preLaunchHelperImpl0.setUpdateUtil(updateUtilImpl0);
      preLaunchHelperImpl0.installUpdates(false);
      assertNull(preLaunchHelperImpl0.getScriptLocation());
  }
}
