/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:12:30 GMT 2020
 */

package org.gudy.azureus2.ui.console.commands;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.aelitis.azureus.activities.VuzeActivitiesEntry;
import com.aelitis.azureus.core.AzureusCore;
import com.aelitis.azureus.core.impl.AzureusCoreImpl;
import com.aelitis.azureus.plugins.dht.DHTPlugin;
import com.aelitis.azureus.ui.common.table.TableColumnCore;
import java.io.File;
import java.io.InputStream;
import java.io.PrintStream;
import java.io.StringReader;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.gudy.azureus2.core3.download.DownloadManager;
import org.gudy.azureus2.core3.global.GlobalMangerProgressListener;
import org.gudy.azureus2.core3.global.impl.GlobalManagerImpl;
import org.gudy.azureus2.core3.torrent.TOTorrent;
import org.gudy.azureus2.ui.console.ConsoleInput;
import org.gudy.azureus2.ui.console.UserProfile;
import org.gudy.azureus2.ui.console.commands.Show;
import org.gudy.azureus2.ui.swt.views.table.impl.TableViewSWTImpl;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Show_ESTest extends Show_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Show show0 = new Show();
      File file0 = MockFile.createTempFile("A?w@o$Aek* CW^\"", "[%a] %c\t%t (%z) ETA: %e\r\n%r\tSpeed: %d%I / %u%O\tAmount: %D / %U\tConnections: %s(%S) / %p(%P)");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, false);
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFileOutputStream0);
      show0.printHelpExtra(mockPrintStream0, (List) null);
      assertEquals(797L, file0.length());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.getDefaultSummaryFormat();
      assertEquals("[%a] %c\t%t (%z) ETA: %e\r\n%r\tSpeed: %d%I / %u%O\tAmount: %D / %U\tConnections: %s(%S) / %p(%P)", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.showDHTStats((ConsoleInput) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Show show0 = new Show();
      Class<InputStream> class0 = InputStream.class;
      TableColumnCore[] tableColumnCoreArray0 = new TableColumnCore[9];
      TableViewSWTImpl<Integer> tableViewSWTImpl0 = new TableViewSWTImpl<Integer>(class0, "pp:lj]#", "pp:lj]#", tableColumnCoreArray0, "s!Yp,-", 100);
      List<Object> list0 = tableViewSWTImpl0.getSelectedDataSources();
      // Undeclared exception!
      try { 
        show0.printHelpExtra((PrintStream) null, list0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Show show0 = new Show();
      LinkedList<DHTPlugin> linkedList0 = new LinkedList<DHTPlugin>();
      // Undeclared exception!
      try { 
        show0.execute("too many seeds", (ConsoleInput) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Show show0 = new Show();
      MockPrintStream mockPrintStream0 = new MockPrintStream("\t\ttransferring\tx\tShow only transferring torrents.");
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      show0.printHelp(mockPrintStream0, linkedList0);
      assertEquals("show [<various options>]\tsh\tShow info. Use without parameter to get a list of available options.", show0.getCommandDescriptions());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.getCommandDescriptions();
      assertEquals("show [<various options>]\tsh\tShow info. Use without parameter to get a list of available options.", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable(')', (DownloadManager) null);
      assertEquals("??)??", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('v', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('r', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('p', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable('k', (DownloadManager) null);
      assertEquals("??k??", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable('i', (DownloadManager) null);
      assertEquals("??i??", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable('g', (DownloadManager) null);
      assertEquals("??g??", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          Show show0 = new Show();
          AzureusCore azureusCore0 = AzureusCoreImpl.create();
          GlobalMangerProgressListener globalMangerProgressListener0 = mock(GlobalMangerProgressListener.class, new ViolatedAssumptionAnswer());
          long long0 = 1L;
          GlobalManagerImpl globalManagerImpl0 = new GlobalManagerImpl(azureusCore0, globalMangerProgressListener0, long0);
          VuzeActivitiesEntry vuzeActivitiesEntry0 = new VuzeActivitiesEntry();
          TOTorrent tOTorrent0 = vuzeActivitiesEntry0.getTorrent();
          DownloadManager downloadManager0 = globalManagerImpl0.getDownloadManager(tOTorrent0);
          char char0 = '_';
          String string0 = show0.expandVariable(char0, downloadManager0);
          assertEquals("??_??", string0);
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable('X', (DownloadManager) null);
      assertEquals("??X??", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('U', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('S', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Show show0 = new Show();
      // Undeclared exception!
      try { 
        show0.expandVariable('O', (DownloadManager) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Show show0 = new Show();
      String string0 = show0.expandVariable('F', (DownloadManager) null);
      assertEquals("??F??", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Show show0 = new Show();
      LinkedList<DHTPlugin> linkedList0 = new LinkedList<DHTPlugin>();
      DHTPlugin dHTPlugin0 = new DHTPlugin();
      linkedList0.add(dHTPlugin0);
      // Undeclared exception!
      try { 
        show0.execute("", (ConsoleInput) null, linkedList0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.aelitis.azureus.plugins.dht.DHTPlugin cannot be cast to java.lang.String
         //
         verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          Show show0 = new Show();
          AzureusCore azureusCore0 = AzureusCoreImpl.create();
          GlobalMangerProgressListener globalMangerProgressListener0 = mock(GlobalMangerProgressListener.class, new ViolatedAssumptionAnswer());
          long long0 = 1L;
          GlobalManagerImpl globalManagerImpl0 = new GlobalManagerImpl(azureusCore0, globalMangerProgressListener0, long0);
          VuzeActivitiesEntry vuzeActivitiesEntry0 = new VuzeActivitiesEntry();
          TOTorrent tOTorrent0 = vuzeActivitiesEntry0.getTorrent();
          DownloadManager downloadManager0 = globalManagerImpl0.getDownloadManager(tOTorrent0);
          // Undeclared exception!
          try { 
            show0.getTorrentSummary(downloadManager0);
            fail("Expecting exception: NullPointerException");
          
          } catch(NullPointerException e) {
             //
             // no message in exception (getMessage() returned null)
             //
             verifyException("org.gudy.azureus2.ui.console.commands.Show", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Show show0 = new Show();
      LinkedList<DHTPlugin> linkedList0 = new LinkedList<DHTPlugin>();
      StringReader stringReader0 = new StringReader("{1");
      MockFile mockFile0 = new MockFile((File) null, "[,67");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0);
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFileOutputStream0);
      Boolean boolean0 = Boolean.TRUE;
      UserProfile userProfile0 = UserProfile.DEFAULT_USER_PROFILE;
      ConsoleInput consoleInput0 = new ConsoleInput("", (AzureusCore) null, stringReader0, mockPrintStream0, boolean0, userProfile0);
      show0.execute("", consoleInput0, linkedList0);
      //  // Unstable assertion: assertEquals(894L, mockFile0.length());
  }
}
