/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu May 07 08:56:34 GMT 2020
 */

package de.huxhorn.lilith.engine;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AccessFileBufferFactory_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "de.huxhorn.lilith.engine.AccessFileBufferFactory"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/test-smell/generation-scripts/projects/43_lilith"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AccessFileBufferFactory_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.protobuf.GeneratedMessage$ExtendableBuilder",
      "com.google.protobuf.DescriptorProtos$MethodOptions$Builder",
      "com.google.protobuf.DescriptorProtos$MethodOptions",
      "com.google.protobuf.Descriptors$1",
      "com.google.protobuf.DescriptorProtos$DescriptorProto",
      "com.google.protobuf.Message$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$LoggerContext$Builder",
      "de.huxhorn.lilith.data.eventsource.SourceIdentifier",
      "com.google.protobuf.DescriptorProtos$ServiceDescriptorProto$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayMap$Builder",
      "org.apache.commons.io.filefilter.EmptyFileFilter",
      "com.google.protobuf.AbstractMessage$Builder$1",
      "de.huxhorn.lilith.engine.AccessFileBufferFactory",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$RepeatedFieldAccessor",
      "com.google.protobuf.DescriptorProtos$MessageOptions",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "com.google.protobuf.DescriptorProtos$EnumValueOptions",
      "com.google.protobuf.Descriptors$ServiceDescriptor",
      "de.huxhorn.sulky.codec.filebuffer.DataStrategy",
      "com.google.protobuf.DescriptorProtos$ServiceOptions",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$AccessEvent",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataEncoder",
      "com.google.protobuf.TextFormat$InvalidEscapeSequence",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$EventWrapper",
      "de.huxhorn.sulky.codec.DelegatingCodecBase",
      "com.google.protobuf.InvalidProtocolBufferException",
      "com.google.protobuf.Descriptors$MethodDescriptor",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "de.huxhorn.sulky.codec.Decoder",
      "com.google.protobuf.DescriptorProtos$MethodDescriptorProto",
      "com.google.protobuf.ByteString$Output",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "com.google.protobuf.ByteString$CodedBuilder",
      "com.google.protobuf.Descriptors$FieldDescriptor$Type",
      "com.google.protobuf.DescriptorProtos$MethodDescriptorProto$Builder",
      "de.huxhorn.lilith.data.access.AccessEvent",
      "com.google.protobuf.GeneratedMessage$GeneratedExtension",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularFieldAccessor",
      "com.google.protobuf.DescriptorProtos$ServiceDescriptorProto",
      "com.google.protobuf.DescriptorProtos$DescriptorProto$Builder",
      "com.google.protobuf.GeneratedMessage$Builder",
      "com.google.protobuf.DescriptorProtos$UninterpretedOption$NamePart",
      "de.huxhorn.sulky.codec.filebuffer.MetaData",
      "com.google.protobuf.DescriptorProtos$EnumDescriptorProto",
      "com.google.protobuf.DescriptorProtos$UninterpretedOption$Builder",
      "com.google.protobuf.UnknownFieldSet$Builder",
      "de.huxhorn.sulky.buffers.FileBuffer",
      "de.huxhorn.sulky.io.IOUtilities",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "com.google.protobuf.Descriptors$GenericDescriptor",
      "de.huxhorn.sulky.buffers.AppendOperation",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable",
      "com.google.protobuf.DescriptorProtos$FieldDescriptorProto",
      "de.huxhorn.sulky.codec.filebuffer.DefaultIndexStrategy",
      "de.huxhorn.lilith.data.eventsource.EventIdentifier",
      "com.google.protobuf.DescriptorProtos$DescriptorProto$ExtensionRange$Builder",
      "com.google.protobuf.UnknownFieldSet$Field$Builder",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$EventIdentifier$Builder",
      "com.google.protobuf.FieldSet",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayValue",
      "de.huxhorn.lilith.engine.FileBufferFactory",
      "com.google.protobuf.Descriptors$FileDescriptor$InternalDescriptorAssigner",
      "de.huxhorn.sulky.codec.filebuffer.FileHeaderStrategy",
      "com.google.protobuf.Descriptors$DescriptorPool",
      "com.google.protobuf.UnknownFieldSet$Field",
      "de.huxhorn.lilith.data.eventsource.TransferSizeInfo",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$LoggerContext",
      "com.google.protobuf.DescriptorProtos$EnumOptions",
      "com.google.protobuf.DescriptorProtos$FieldOptions",
      "com.google.protobuf.Descriptors$EnumValueDescriptor",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayValue$Builder",
      "org.apache.commons.io.filefilter.WildcardFilter",
      "de.huxhorn.lilith.data.eventsource.EventWrapper",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$RepeatedMessageFieldAccessor",
      "de.huxhorn.lilith.engine.LogFileFactory",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayMap",
      "com.google.protobuf.GeneratedMessage$ExtendableMessage",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "com.google.protobuf.DescriptorProtos",
      "com.google.protobuf.ProtocolMessageEnum",
      "com.google.protobuf.DescriptorProtos$FileDescriptorProto$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayMapEntry",
      "de.huxhorn.sulky.codec.Encoder",
      "com.google.protobuf.AbstractMessage$Builder",
      "com.google.protobuf.Descriptors$DescriptorPool$DescriptorIntPair",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$FieldAccessor",
      "de.huxhorn.sulky.buffers.ResetOperation",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufCodec",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringMap$Builder",
      "com.google.protobuf.DescriptorProtos$FileOptions",
      "com.google.protobuf.DescriptorProtos$1",
      "com.google.protobuf.DescriptorProtos$EnumValueOptions$Builder",
      "de.huxhorn.lilith.swing.filefilters.LogFileFilter",
      "com.google.protobuf.DescriptorProtos$FieldOptions$CType",
      "de.huxhorn.sulky.codec.Codec",
      "com.google.protobuf.Descriptors$DescriptorValidationException",
      "com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$AccessEvent$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringMap",
      "de.huxhorn.lilith.data.access.LoggerContext",
      "com.google.protobuf.DescriptorProtos$MessageOptions$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$1",
      "de.huxhorn.sulky.codec.filebuffer.FileHeader",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "com.google.protobuf.DescriptorProtos$UninterpretedOption$NamePart$Builder",
      "com.google.protobuf.DescriptorProtos$FileDescriptorProto",
      "com.google.protobuf.DescriptorProtos$EnumValueDescriptorProto",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringArrayMapEntry$Builder",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "com.google.protobuf.ByteString",
      "com.google.protobuf.UninitializedMessageException",
      "com.google.protobuf.Descriptors$FieldDescriptor",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringMapEntry$Builder",
      "com.google.protobuf.CodedOutputStream$OutOfSpaceException",
      "com.google.protobuf.GeneratedMessage$ExtendableMessage$ExtensionWriter",
      "de.huxhorn.sulky.codec.filebuffer.DefaultDataStrategy",
      "org.apache.commons.io.filefilter.FalseFileFilter",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularMessageFieldAccessor",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataDecoder",
      "com.google.protobuf.DescriptorProtos$FileOptions$Builder",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "com.google.protobuf.Descriptors$FileDescriptor",
      "org.apache.commons.io.FilenameUtils",
      "de.huxhorn.sulky.codec.filebuffer.IndexStrategy",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$EventIdentifier",
      "org.apache.commons.io.IOCase",
      "de.huxhorn.lilith.data.access.protobuf.CompressingAccessEventWrapperProtobufCodec",
      "com.google.protobuf.Descriptors",
      "com.google.protobuf.Descriptors$FieldDescriptor$JavaType",
      "com.google.protobuf.DescriptorProtos$EnumOptions$Builder",
      "com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularEnumFieldAccessor",
      "de.huxhorn.sulky.codec.filebuffer.CodecFileBuffer",
      "com.google.protobuf.DescriptorProtos$EnumDescriptorProto$Builder",
      "com.google.protobuf.DescriptorProtos$FileOptions$OptimizeMode",
      "com.google.protobuf.DescriptorProtos$ServiceOptions$Builder",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufDecoder",
      "de.huxhorn.sulky.buffers.DisposeOperation",
      "com.google.protobuf.Descriptors$DescriptorPool$PackageDescriptor",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataCodec",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "com.google.protobuf.DescriptorProtos$FieldOptions$Builder",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$EventWrapper$Builder",
      "com.google.protobuf.GeneratedMessage",
      "com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Type",
      "com.google.protobuf.Descriptors$EnumDescriptor",
      "com.google.protobuf.CodedOutputStream",
      "com.google.protobuf.ExtensionRegistry$ExtensionInfo",
      "com.google.protobuf.UnknownFieldSet",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$StringMapEntry",
      "de.huxhorn.sulky.buffers.Buffer",
      "com.google.protobuf.AbstractMessage",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$SourceIdentifier$Builder",
      "com.google.protobuf.DescriptorProtos$UninterpretedOption",
      "de.huxhorn.lilith.data.access.protobuf.generated.AccessProto$SourceIdentifier",
      "com.google.protobuf.Descriptors$Descriptor",
      "com.google.protobuf.DescriptorProtos$DescriptorProto$ExtensionRange",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufEncoder",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "com.google.protobuf.DescriptorProtos$FileDescriptorSet",
      "de.huxhorn.sulky.codec.filebuffer.DefaultFileHeaderStrategy",
      "com.google.protobuf.CodedInputStream",
      "de.huxhorn.sulky.buffers.SetOperation",
      "com.google.protobuf.ExtensionRegistry",
      "com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Label",
      "com.google.protobuf.Message",
      "com.google.protobuf.DescriptorProtos$EnumValueDescriptorProto$Builder",
      "de.huxhorn.lilith.engine.impl.LogFileFactoryImpl",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "com.google.protobuf.DescriptorProtos$FileDescriptorSet$Builder"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AccessFileBufferFactory_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "de.huxhorn.lilith.engine.FileBufferFactory",
      "de.huxhorn.lilith.engine.AccessFileBufferFactory",
      "de.huxhorn.lilith.engine.impl.LogFileFactoryImpl",
      "de.huxhorn.lilith.data.access.AccessEvent",
      "de.huxhorn.lilith.data.eventsource.SourceIdentifier",
      "de.huxhorn.sulky.codec.filebuffer.MetaData",
      "de.huxhorn.lilith.data.eventsource.EventWrapper",
      "de.huxhorn.lilith.data.eventsource.EventIdentifier",
      "de.huxhorn.sulky.codec.filebuffer.CodecFileBuffer",
      "de.huxhorn.sulky.codec.filebuffer.DefaultFileHeaderStrategy",
      "de.huxhorn.sulky.codec.DelegatingCodecBase",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataCodec",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataEncoder",
      "de.huxhorn.sulky.codec.filebuffer.MetaDataDecoder",
      "de.huxhorn.sulky.codec.filebuffer.DefaultIndexStrategy",
      "de.huxhorn.lilith.data.access.LoggerContext",
      "de.huxhorn.sulky.codec.filebuffer.FileHeader",
      "de.huxhorn.sulky.codec.filebuffer.DefaultDataStrategy",
      "de.huxhorn.sulky.io.IOUtilities",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufCodec",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufEncoder",
      "de.huxhorn.lilith.data.access.protobuf.AccessEventWrapperProtobufDecoder",
      "de.huxhorn.lilith.data.eventsource.TransferSizeInfo",
      "de.huxhorn.lilith.data.access.protobuf.CompressingAccessEventWrapperProtobufCodec",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.io.filefilter.WildcardFilter",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "org.apache.commons.io.filefilter.EmptyFileFilter",
      "org.apache.commons.io.filefilter.FalseFileFilter",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "de.huxhorn.lilith.swing.filefilters.LogFileFilter"
    );
  }
}
