/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun May 10 18:25:04 GMT 2020
 */

package de.huxhorn.lilith.consumers;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class AlarmSoundLoggingEventConsumer_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/Users/ubuntulla/Desktop/EvoSuite/EvoSuite_from_github/workspace/LunchEvosuite"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/dv/v0mssygs4vb7wyc17m7j2c5w0000gn/T/"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AlarmSoundLoggingEventConsumer_ESTest_scaffolding.class.getClassLoader() ,
      "de.huxhorn.lilith.data.logging.LoggingEvent",
      "de.huxhorn.lilith.data.logging.LoggerContext",
      "de.huxhorn.sulky.sounds.jlayer.JLayerSounds",
      "de.huxhorn.lilith.data.logging.ThrowableInfo",
      "de.huxhorn.sulky.sounds.Sounds",
      "de.huxhorn.lilith.data.eventsource.TransferSizeInfo",
      "de.huxhorn.lilith.data.eventsource.SourceIdentifier",
      "de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer",
      "de.huxhorn.lilith.data.logging.Marker",
      "de.huxhorn.lilith.data.eventsource.EventIdentifier",
      "de.huxhorn.lilith.data.logging.ExtendedStackTraceElement",
      "de.huxhorn.lilith.engine.EventConsumer",
      "de.huxhorn.lilith.data.logging.ThreadInfo",
      "de.huxhorn.lilith.data.logging.LoggingEvent$Level",
      "de.huxhorn.lilith.data.eventsource.EventWrapper",
      "de.huxhorn.lilith.data.logging.Message",
      "javazoom.jl.decoder.JavaLayerException",
      "de.huxhorn.sulky.sounds.jlayer.JLayerSounds$PlayRunnable"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AlarmSoundLoggingEventConsumer_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "de.huxhorn.lilith.consumers.AlarmSoundLoggingEventConsumer",
      "de.huxhorn.lilith.data.logging.LoggingEvent$Level",
      "de.huxhorn.sulky.sounds.jlayer.JLayerSounds",
      "de.huxhorn.sulky.sounds.jlayer.JLayerSounds$PlayRunnable",
      "de.huxhorn.lilith.data.eventsource.EventWrapper",
      "de.huxhorn.lilith.data.eventsource.EventIdentifier",
      "de.huxhorn.lilith.data.eventsource.SourceIdentifier",
      "de.huxhorn.lilith.data.logging.LoggingEvent",
      "de.huxhorn.lilith.data.logging.ExtendedStackTraceElement",
      "de.huxhorn.lilith.data.logging.LoggerContext",
      "de.huxhorn.lilith.data.logging.ThrowableInfo",
      "de.huxhorn.lilith.data.logging.Marker",
      "de.huxhorn.lilith.data.eventsource.TransferSizeInfo",
      "de.huxhorn.lilith.data.logging.ThreadInfo",
      "de.huxhorn.lilith.data.logging.Message"
    );
  }
}
