/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:17:15 GMT 2020
 */

package com.liferay.portal.kernel.notifications;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.json.JSONObjectImpl;
import com.liferay.portal.kernel.notifications.NotificationEvent;
import com.liferay.portal.kernel.notifications.NotificationEventComparator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

 
public class NotificationEventComparatorTest { 

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NotificationEventComparator notificationEventComparator0 = new NotificationEventComparator(false);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NotificationEventComparator notificationEventComparator0 = new NotificationEventComparator();
      JSONObjectImpl jSONObjectImpl0 = new JSONObjectImpl();
      NotificationEvent notificationEvent0 = new NotificationEvent(0L, "%7xDPq8", jSONObjectImpl0);
      notificationEvent0.setUuid("%7xDPq8");
      int int0 = notificationEventComparator0.compare(notificationEvent0, notificationEvent0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NotificationEventComparator notificationEventComparator0 = new NotificationEventComparator();
      JSONObjectImpl jSONObjectImpl0 = new JSONObjectImpl();
      NotificationEvent notificationEvent0 = new NotificationEvent(0L, "{", jSONObjectImpl0);
      // Undeclared exception!
      try { 
        notificationEventComparator0.compare(notificationEvent0, (NotificationEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.notifications.NotificationEventComparator", e);
      }
  }
}
