/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu May 07 08:27:39 GMT 2020
 */

package org.heal.module.metadata;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class CompleteMetadataBean_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.heal.module.metadata.CompleteMetadataBean"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/home/test-smell/generation-scripts/projects/96_heal"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CompleteMetadataBean_ESTest_scaffolding.class.getClassLoader() ,
      "org.heal.module.metadata.ShortMetadataBean",
      "org.heal.module.metadata.ThumbnailBean",
      "org.heal.module.metadata.MetadataBean",
      "org.heal.module.metadata.DiseaseDiagnosisBean",
      "org.heal.module.metadata.TargetUserGroupBean",
      "org.heal.module.metadata.CompleteMetadataBean",
      "org.heal.module.metadata.CopyrightTextBean",
      "org.heal.module.metadata.TaxonPathBean",
      "org.heal.module.metadata.SourceCollectionBean",
      "org.heal.util.DateTools",
      "org.heal.module.metadata.RequirementBean",
      "org.heal.module.metadata.ContributorBean",
      "org.heal.module.metadata.TaxonBean",
      "org.heal.module.metadata.CopyrightHolderBean",
      "org.heal.module.metadata.CopyrightBean",
      "org.heal.module.metadata.ContextURLBean",
      "org.heal.module.metadata.FormatBean",
      "org.heal.module.metadata.RelationBean",
      "org.heal.module.metadata.KeywordBean"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CompleteMetadataBean_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.heal.module.metadata.ShortMetadataBean",
      "org.heal.module.metadata.MetadataBean",
      "org.heal.module.metadata.CompleteMetadataBean",
      "org.heal.module.metadata.RequirementBean",
      "org.heal.module.metadata.RelationBean",
      "org.heal.module.metadata.TargetUserGroupBean",
      "org.heal.module.metadata.CopyrightHolderBean",
      "org.heal.module.metadata.CopyrightBean",
      "org.heal.util.DateTools",
      "org.heal.module.metadata.DiseaseDiagnosisBean",
      "org.heal.module.metadata.ContributorBean",
      "org.heal.module.metadata.ContextURLBean",
      "org.heal.module.metadata.FormatBean",
      "org.heal.module.metadata.KeywordBean",
      "org.heal.module.metadata.TaxonPathBean",
      "org.heal.module.metadata.SourceCollectionBean",
      "org.heal.module.metadata.CopyrightTextBean",
      "org.heal.module.metadata.ThumbnailBean",
      "org.heal.module.metadata.TaxonBean"
    );
  }
}
