/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:32:40 GMT 2020
 */

package com.liferay.portal.kernel.messaging.proxy;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.liferay.portal.kernel.messaging.DefaultMessageBus;
import com.liferay.portal.kernel.messaging.Message;
import com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.testng.TestNG;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProxyMessageListener_ESTest extends ProxyMessageListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProxyMessageListener proxyMessageListener0 = new ProxyMessageListener();
      Message message0 = new Message();
      proxyMessageListener0.receive(message0);
      assertNull(message0.getDestinationName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProxyMessageListener proxyMessageListener0 = new ProxyMessageListener();
      Message message0 = new Message();
      message0.setResponseDestinationName("_3K(");
      // Undeclared exception!
      try { 
        proxyMessageListener0.receive(message0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProxyMessageListener proxyMessageListener0 = new ProxyMessageListener();
      Message message0 = new Message();
      message0.setPayload(proxyMessageListener0);
      proxyMessageListener0.receive(message0);
      assertNull(message0.getResponseDestinationName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProxyMessageListener proxyMessageListener0 = new ProxyMessageListener();
      DefaultMessageBus defaultMessageBus0 = new DefaultMessageBus();
      proxyMessageListener0.setMessageBus(defaultMessageBus0);
      assertEquals(0, defaultMessageBus0.getDestinationCount());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProxyMessageListener proxyMessageListener0 = new ProxyMessageListener();
      Integer integer0 = TestNG.DEFAULT_VERBOSE;
      proxyMessageListener0.setManager(integer0);
  }
}
