/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:47:42 GMT 2020
 */

package com.yahoo.platform.yui.compressor;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.yahoo.platform.yui.compressor.JavaScriptIdentifier;
import com.yahoo.platform.yui.compressor.ScriptOrFnScope;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

 
public class ScriptOrFnScopeTest { 

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      ScriptOrFnScope scriptOrFnScope1 = new ScriptOrFnScope((-330), scriptOrFnScope0);
      ScriptOrFnScope scriptOrFnScope2 = scriptOrFnScope1.getParentScope();
      assertSame(scriptOrFnScope0, scriptOrFnScope2);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope(2362, (ScriptOrFnScope) null);
      JavaScriptIdentifier javaScriptIdentifier0 = scriptOrFnScope0.declareIdentifier("interface");
      JavaScriptIdentifier javaScriptIdentifier1 = scriptOrFnScope0.getIdentifier("interface");
      assertSame(javaScriptIdentifier1, javaScriptIdentifier0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope(0, (ScriptOrFnScope) null);
      int int0 = scriptOrFnScope0.getBraceNesting();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope(153, (ScriptOrFnScope) null);
      int int0 = scriptOrFnScope0.getBraceNesting();
      assertEquals(153, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-2210), (ScriptOrFnScope) null);
      // Undeclared exception!
      try { 
        scriptOrFnScope0.getIdentifier((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-2211), (ScriptOrFnScope) null);
      // Undeclared exception!
      try { 
        scriptOrFnScope0.declareIdentifier((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope(1465, (ScriptOrFnScope) null);
      // Undeclared exception!
      try { 
        scriptOrFnScope0.addHint((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Hashtable", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      ScriptOrFnScope scriptOrFnScope1 = new ScriptOrFnScope((-330), scriptOrFnScope0);
      scriptOrFnScope1.preventMunging();
      scriptOrFnScope1.munge();
      assertNotSame(scriptOrFnScope0, scriptOrFnScope1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      ScriptOrFnScope scriptOrFnScope1 = new ScriptOrFnScope((-330), scriptOrFnScope0);
      scriptOrFnScope1.declareIdentifier("");
      ScriptOrFnScope scriptOrFnScope2 = new ScriptOrFnScope((-4926), scriptOrFnScope1);
      scriptOrFnScope0.munge();
      assertNotSame(scriptOrFnScope0, scriptOrFnScope1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      ScriptOrFnScope scriptOrFnScope1 = new ScriptOrFnScope((-330), scriptOrFnScope0);
      scriptOrFnScope1.munge();
      assertNotSame(scriptOrFnScope1, scriptOrFnScope0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      scriptOrFnScope0.preventMunging();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      JavaScriptIdentifier javaScriptIdentifier0 = scriptOrFnScope0.declareIdentifier("");
      JavaScriptIdentifier javaScriptIdentifier1 = scriptOrFnScope0.declareIdentifier("");
      assertSame(javaScriptIdentifier1, javaScriptIdentifier0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      int int0 = scriptOrFnScope0.incrementVarCount();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      scriptOrFnScope0.addHint("", "");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      ScriptOrFnScope scriptOrFnScope1 = scriptOrFnScope0.getParentScope();
      assertNull(scriptOrFnScope1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-806), (ScriptOrFnScope) null);
      JavaScriptIdentifier javaScriptIdentifier0 = scriptOrFnScope0.getIdentifier("znQlJ:cAw(");
      assertNull(javaScriptIdentifier0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ScriptOrFnScope scriptOrFnScope0 = new ScriptOrFnScope((-2726), (ScriptOrFnScope) null);
      int int0 = scriptOrFnScope0.getBraceNesting();
      assertEquals((-2726), int0);
  }
}
