/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 08:21:34 GMT 2020
 */

package org.pdfsam.guiclient.commons.dnd.droppers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.awt.dnd.DropTargetDropEvent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.pdfsam.guiclient.business.ClosableTabbedPanelAdder;
import org.pdfsam.guiclient.commons.dnd.droppers.JVisualMultiSelectionDropper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractDropper_ESTest extends AbstractDropper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JVisualMultiSelectionDropper jVisualMultiSelectionDropper0 = new JVisualMultiSelectionDropper((ClosableTabbedPanelAdder) null);
      // Undeclared exception!
      try { 
        jVisualMultiSelectionDropper0.drop((DropTargetDropEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.pdfsam.guiclient.configuration.Configuration", e);
      }
  }
}
