/*
 * This file was automatically generated by EvoSuite
 * Thu May 07 09:05:19 GMT 2020
 */

package weka.core;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import weka.core.Version;

 
public class VersionTest { 

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("4-)");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Version version0 = new Version();
      Version.VERSION = null;
      String string0 = version0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Version version0 = new Version();
      Version.VERSION = "";
      String string0 = version0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      boolean boolean0 = version0.isNewer(object0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Version version0 = new Version();
      boolean boolean0 = version0.isNewer("8034");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Version version0 = new Version();
      boolean boolean0 = version0.equals(version0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Version version0 = new Version();
      boolean boolean0 = version0.equals("3.7.7");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = 1903;
      int int0 = version0.compareTo("3.7.7");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = 4;
      int int0 = version0.compareTo("3.7.7");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Version version0 = new Version();
      Version.MINOR = 220;
      int int0 = version0.compareTo("3.7.7");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Version version0 = new Version();
      Version.MINOR = (-832);
      int int0 = version0.compareTo("3.7.7");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("3.7.7");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("8034");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo(version0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Version.MINOR = 4;
      String[] stringArray0 = new String[0];
      Version.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Version version0 = new Version();
      Version.REVISION = (-2231);
      boolean boolean0 = version0.isOlder("3.7.7");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Version version0 = new Version();
      Object object0 = new Object();
      boolean boolean0 = version0.isOlder(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Version version0 = new Version();
      int int0 = version0.compareTo("");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Version version0 = new Version();
      String string0 = version0.toString();
      assertEquals("3.7.7", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Version version0 = new Version();
      String string0 = version0.getRevision();
      assertEquals("8034", string0);
  }
}
